version: 2
updates:
  - package-ecosystem: maven
    directory: /
    schedule:
      interval: daily
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
      day: monday
  - package-ecosystem: maven
    directory: /
    target-branch: 3.x
    schedule:
      interval: daily
    ignore:
      - dependency-name: io.micronaut:*
        update-types: [version-update:semver-major]
  - package-ecosystem: github-actions
    directory: /
    target-branch: 3.x
    schedule:
      interval: monthly
      day: monday
