version: 2
updates:
  - package-ecosystem: maven
    directory: /
    open-pull-requests-limit: 20
    schedule:
      interval: monthly
      day: monday
      # github parses time without quotes to int
      # yamllint disable-line rule:quoted-strings
      time: "09:00"
      timezone: Europe/Berlin
  - package-ecosystem: maven
    directory: /
    open-pull-requests-limit: 20
    schedule:
      interval: monthly
      day: monday
      # github parses time without quotes to int
      # yamllint disable-line rule:quoted-strings
      time: "09:00"
      timezone: Europe/Berlin
    target-branch: 3.x
    ignore:
      # logback 1.3 and 1.4 are compatible with slf4j 2.x only and not supported right now
      - dependency-name: ch.qos.logback:logback-classic
        update-types: [version-update:semver-major, version-update:semver-minor]
      - dependency-name: org.slf4j:slf4j-api
        update-types: [version-update:semver-major]
      # micronaut 4 will ship logback 1.4
      - dependency-name: io.micronaut:*
        update-types: [version-update:semver-major]
  - package-ecosystem: github-actions
    directory: /
    open-pull-requests-limit: 10
    schedule:
      interval: monthly
      day: monday
      # github parses time without quotes to int
      # yamllint disable-line rule:quoted-strings
      time: "09:00"
      timezone: Europe/Berlin
