version: 2
updates:
  - package-ecosystem: maven
    directory: /
    schedule:
      interval: daily
    ignore:
      - dependency-name: ch.qos.logback:logback-classic
        update-types: ["version-update:semver-major"]
      - dependency-name: io.micronaut:micronaut-bom
        update-types: ["version-update:semver-major"]
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
