when:
  instance: ci.kokuwa.io
  repo: kokuwaio/micronaut-logging
  event: [manual, push]
  branch: main
  path: [.woodpecker/deploy.yaml, pom.xml, src/main/**]

steps:

  maven:
    image: maven:3.9.11-eclipse-temurin-17
    commands: mvn deploy -Pdeploy --settings=.woodpecker/maven/settings.xml
    environment:
      MAVEN_GPG_KEY: {from_secret: woodpecker_gpg_key}
      SONATYPE_ORG_USERNAME: {from_secret: sonatype_org_username}
      SONATYPE_ORG_PASSWORD: {from_secret: sonatype_org_password}
